name: HopperFilter
version: ${version}
main: io.github.anomalyforlife.hopperFilter.HopperFilter
api-version: "1.21.4"

commands:
  hopperfilter:
    description: HopperFilter admin commands
    usage: "/hopperfilter <reload|info|clear|give|giveconverter|converthopper|convertradius|maxupgrade|upgraderadius>"
    aliases: [ hf ]

permissions:
  hopperfilter.opengui:
    description: Allows opening the hopper filter GUI
    default: op
  hopperfilter.use:
    description: Allows using the hopper filter GUI (add/remove items)
    default: op
  hopperfilter.break:
    description: Allows breaking filtered hoppers (must sneak)
    default: op
  hopperfilter.admin.reload:
    description: Allows reloading HopperFilter config
    default: op
  hopperfilter.admin.info:
    description: Allows viewing hopper filter info
    default: op
  hopperfilter.admin.clear:
    description: Allows clearing hopper filters via command
    default: op
  hopperfilter.admin.give:
    description: Allows giving special Filtered Hoppers and Hopper Converters via command
    default: op
  hopperfilter.convert:
    description: Allows using the Hopper Converter item to convert hoppers
    default: op
  hopperfilter.admin.convert:
    description: Allows converting hoppers to filtered hoppers via /hf converthopper and /hf convertradius
    default: op

libraries:
  - org.xerial:sqlite-jdbc:3.45.3.0
  - com.mysql:mysql-connector-j:8.3.0
  - com.google.code.gson:gson:2.10.1